#!/usr/bin/env bash
#installing and configuration of nginx

apt-get remove nginx nginx-common nginx-full nginx-core -y
apt-get purge nginx nginx-common nginx-full nginx-core -y
apt autoremove -y
apt-get update -y
apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.html

nginx -s reload
