#!/usr/bin/env bash
#installing and configuration of nginx

sudo apt-get update -y
sudo apt-get install nginx -y

mkdir -p /web
echo "Hello World!" > /web/0-index.html;

echo "user ubuntu;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 768;
    # multi_accept on;
}

http {
        server {
                listen 80 default_server;
                location / {
                        root /web;
                        index 0-index.html;
                }
        }
}" >/etc/nginx/nginx.conf
nginx -s reload
