#!/usr/bin/env bash
#installing and configuration of nginx

sudo apt-get update -y
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
if [ -f /var/www/html/index.nginx-debian.html ];
then
	mv /var/www/html/index.nginx-debian.html /var/www/html/index.html
fi
echo "Hello World" > /var/www/html/html
sudo service nginx start
