#!/usr/bin/env bash
# web redirection
#parmanent redirection

apt-get update
apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
service nginx start

sed -i '/server_name _;/a\ \tlocation /redirect_me/{\n\t\treturn 301; \n\t}'\
 /etc/nginx/sites-available/default

nginx -s reload
