#!/usr/bin/env bash
# web redirection
#parmanent redirection

udo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx start

sed -i '/server_name _;/a\ \tlocation /redirect_me/{\n\t\treturn 301; \n\t}'\
 /etc/nginx/sites-available/default

sudo nginx -s reload
