#!/usr/bin/env bash
# Add redirection location block
#!/usr/bin/env bash
#nginx configuration and installation 

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sed -i '/server_name _;/a\ \tlocation /redirect_me/{\n\t\treturn 301; \n\t}'\
 /etc/nginx/sites-available/default

sudo service nginx start
