#!/usr/bin/env bash
#installing and configuration of nginx
#landing page cnfig
#redirction config
#erro page config
#serviced by server? config

sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx start

sed -i '/server_name _;/a\ \tlocation /redirect_me/{\n\t\treturn 301; \n\t}'\
 /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/server_name _;/a\\terror_page 404 /404.html;' \
/etc/nginx/sites-available/default

sed -i "/server_name _;/a\\\tadd_header X-Served-By \$hostname;" \
/etc/nginx/sites-available/default

sudo service nginx restart
