#!/usr/bin/env bash
#while and if elif else conditional statement
str='Best School'
i=1
while [[ $i -le 10 ]];
do
	if [ $((i)) == 4 ];
	then
		echo "bad luck"
	elif [ $((i)) == 8 ];
	then
		echo "good luck"
	else
		echo "$str"
	fi
  ((i += 1))
done
