#!/usr/bin/env bash

i=1
while [[ $i -lt 21 ]];
do
	echo "$i"
	if [ $((i)) == 4 ];
	then
		echo "bad luck from china"
	elif [ $((i)) == 9 ];
	then
		echo "bad luck from japan"
	elif [ $((i)) == 17 ];
	then
		echo "bad luck from italy"
	fi
  (( i += 1 ))
done
