#!/usr/bin/env bash
#configuring ~/.ssh/config to refuse password authentication
#and use ~/.ssh/school

echo "IdentityFile ~/.ssh/school" >> ~/.ssh/config
echo "PasswordAuthentication no" >> ~/.ssh/config
